name: |
  Ensure static content builds successfully.

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - 'pills/**'
      - 'book.toml'
      - 'custom.css'
      - 'nix/pkgs/mdbook-sitemap-generator.nix'
  schedule:
    - cron: '0 12 * * 6' # every saturday at noon (UTC)
  workflow_dispatch: # allow to trigger the workflow manually

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nix_channel:
          - nixos-unstable
          - nixos-25.11
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Install Nix
        uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          nix_path: nixpkgs=channel:${{ matrix.nix_channel }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - name: Build static sources
        run: nix-build -A html-split
